# -*- coding: utf-8 -*-
"""pg_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJXkoshZalhprCR81jbCA3pp7Qr4dJ1x
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# Change to the unzipped directory
# %cd /content/drive/MyDrive/Prince_Ndanyuzwe_rl_summative-main

# !pip install stable-baselines3
import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.evaluation import evaluate_policy
from environment.custom_env import PatientMonitoringEnv
import os

# Create log directory
log_dir = "./logs/"
os.makedirs(log_dir, exist_ok=True)

# Initialize the environment
env = PatientMonitoringEnv()

# Define the PPO model
model = PPO(
    "MlpPolicy",  # Use a simple MLP policy
    env,
    verbose=1,
    tensorboard_log=log_dir,
    learning_rate=0.0003,
    gamma=0.99,
    n_steps=2048,
    batch_size=64,
    ent_coef=0.01,  # Encourages exploration
)

# Train the model
TIMESTEPS = 100_000
model.learn(total_timesteps=TIMESTEPS, log_interval=10)

# Save the trained model
model_path = "./models/pg/pg_training"
os.makedirs("./models/pg", exist_ok=True)
model.save(model_path)
print(f"Model saved to {model_path}")